"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { api, getSession, saveSession, SessionUser } from "@/lib/api";

export default function CandidateProfilePage() {
  const [user, setUser] = useState<SessionUser | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const session = getSession(); if (!session) return; api.myProfile(session.token).then(setUser).catch((e: Error) => setError(e.message)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const session = getSession(); if (!session) return; const form = new FormData(event.currentTarget); setSaving(true); setError(""); try { const updated = await api.updateProfile({ nome: String(form.get("nome")), localizacao: String(form.get("localizacao")) || null, experiencia: String(form.get("experiencia")) || null, competencias: String(form.get("competencias")).split(",").map((item) => item.trim()).filter(Boolean), linkedin_url: String(form.get("linkedin_url")) || null, github_url: String(form.get("github_url")) || null }, session.token); setUser(updated); saveSession(session.token, updated); setMessage("Perfil atualizado."); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível atualizar o perfil."); } finally { setSaving(false); } }
  if (!getSession()) return <section className="rounded-xl border border-slate-200 bg-white p-8"><h1 className="text-2xl font-bold">Entre para gerir o perfil</h1><Link href="/auth" className="mt-4 inline-block font-semibold text-sky-700">Entrar →</Link></section>;
  return <section className="max-w-2xl rounded-xl border border-slate-200 bg-white p-7 shadow-sm"><h1 className="text-2xl font-bold text-slate-950">Meu perfil profissional</h1><p className="mt-2 text-slate-600">Estes dados ajudam as empresas a conhecerem a sua experiência durante a triagem.</p><form key={user?.id} onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Nome<input required name="nome" defaultValue={user?.nome} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Localização<input name="localizacao" defaultValue={user?.localizacao ?? ""} placeholder="Ex.: Luanda" className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium sm:col-span-2">E-mail<input disabled value={user?.email ?? ""} className="mt-1 w-full rounded-md border border-slate-200 bg-slate-100 px-3 py-2 text-slate-500" /></label><label className="block text-sm font-medium sm:col-span-2">Experiência<textarea name="experiencia" rows={4} defaultValue={user?.experiencia ?? ""} placeholder="Descreva a sua experiência profissional" className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium sm:col-span-2">Competências<input name="competencias" defaultValue={user?.competencias?.join(", ") ?? ""} placeholder="Ex.: React, Excel, Atendimento" className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">LinkedIn<input type="url" name="linkedin_url" defaultValue={user?.linkedin_url ?? ""} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">GitHub<input type="url" name="github_url" defaultValue={user?.github_url ?? ""} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><div className="sm:col-span-2"><button disabled={saving} className="rounded-md bg-sky-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60">{saving ? "A guardar…" : "Guardar alterações"}</button></div></form>{message && <p className="mt-4 text-sm text-emerald-700">{message}</p>}{error && <p className="mt-4 text-sm text-red-700">{error}</p>}</section>;
}
