"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, getSession, saveSession, SessionUser } from "@/lib/api";

export default function CompanyProfilePage() {
  const [company, setCompany] = useState<SessionUser | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const session = getSession(); if (session) api.myProfile(session.token).then(setCompany).catch((e: Error) => setError(e.message)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const session = getSession(); if (!session) return; const form = new FormData(event.currentTarget); setSaving(true); try { const updated = await api.updateProfile({ nome: String(form.get("nome")), localizacao: String(form.get("localizacao")) || null, experiencia: String(form.get("experiencia")) || null, competencias: String(form.get("competencias")).split(",").map((item) => item.trim()).filter(Boolean), linkedin_url: String(form.get("linkedin_url")) || null, github_url: String(form.get("github_url")) || null }, session.token); setCompany(updated); saveSession(session.token, updated); setMessage("Perfil institucional atualizado."); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível guardar o perfil."); } finally { setSaving(false); } }
  return <section className="max-w-2xl rounded-xl border border-slate-200 bg-white p-7 shadow-sm"><h1 className="text-2xl font-bold text-slate-950">Perfil da empresa</h1><p className="mt-2 text-slate-600">Apresente a empresa a candidatos e organize os dados institucionais.</p><form key={company?.id} onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Nome da empresa<input required name="nome" defaultValue={company?.nome} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Sede/localização<input name="localizacao" defaultValue={company?.localizacao ?? ""} placeholder="Ex.: Luanda" className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium sm:col-span-2">Sobre a empresa<textarea name="experiencia" rows={5} defaultValue={company?.experiencia ?? ""} placeholder="Setor, missão, cultura e dimensão da empresa" className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium sm:col-span-2">Áreas de atuação<input name="competencias" defaultValue={company?.competencias?.join(", ") ?? ""} placeholder="Ex.: Tecnologia, Consultoria, Saúde" className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">LinkedIn<input type="url" name="linkedin_url" defaultValue={company?.linkedin_url ?? ""} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Website<input type="url" name="github_url" defaultValue={company?.github_url ?? ""} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><div className="sm:col-span-2"><button disabled={saving} className="rounded-md bg-sky-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60">{saving ? "A guardar…" : "Guardar perfil"}</button></div></form>{message && <p className="mt-4 text-sm text-emerald-700">{message}</p>}{error && <p className="mt-4 text-sm text-red-700">{error}</p>}</section>;
}
